export const ADD_BUSINESS = 'ADD_BUSINESS';
export const SWITCH_BUSINESS_TAB = 'SWITCH_BUSINESS_TAB';

export const SAVE_CURRENT_STOPWATCH_TIME = 'SAVE_CURRENT_STOPWATCH_TIME';
export const CLEAR_CURRENT_STOPWATCH_TIME = 'CLEAR_CURRENT_STOPWATCH_TIME';

export const SAVE_TIMER_TIME = 'SAVE_TIMER_TIME';
export const CLEAR_CURRENT_COUNTDOWN_TIME = 'CLEAR_CURRENT_COUNTDOWN_TIME';

